### ISSUE TITLE
doesn't connect to voice channels

### ISSUE THREAD

**Issue by RakibRyan** [pawel02/image_bot#7]
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "p" is not found

**Comment by SysAdmin74** [comment]
I think you will have to use -play to run the command. Since that one does work

**Comment by Petrolls** [comment]
I am also having an issue with the bot not connecting to voice chat. The "/help" and "/clear amount" are the only commands that work, everything thing else does not, unfortunately.
